version: "3.4"

services:
  eventstore.db:
    image: eventstore/eventstore:20.10.2-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - 2113:2113
        
  mongo.habit.db:
    image: mongo:latest
    ports:
      - 27017:27017
    
  mongo.user.db:
    image: mongo:latest
    ports:
      - 27018:27017
