name: Docker

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata for Habit.API
        id: meta-habit-api
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-habit-api

      - name: Build and push Docker image for Habit.API
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Habit.API/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-habit-api.outputs.tags }}
          labels: ${{ steps.meta-habit-api.outputs.labels }}

      - name: Extract Docker metadata for Habit.Worker
        id: meta-habit-worker
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-habit-worker
          
      - name: Build and push Docker image for Habit.Worker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Habit.Worker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-habit-worker.outputs.tags }}
          labels: ${{ steps.meta-habit-worker.outputs.labels }}

      - name: Extract Docker metadata for Identity.API
        id: meta-identity-api
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-identity-api
          
      - name: Build and push Docker image for Identity.API
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Identity.API/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-identity-api.outputs.tags }}
          labels: ${{ steps.meta-identity-api.outputs.labels }}